### ISSUE TITLE
Rule By domain

### ISSUE THREAD

**Issue by jrzeponi** [nitmir/policyd-rate-limit#28]
I rewrite file 'policyd_rate_limit/policyd.py' to be possible alocate rule by domain instead account only, this is usefull when I has a domain in server is very important or different rule for all account in this domain

```DIFF
--- /usr/lib/python3/dist-packages/policyd_rate_limit/policyd_BKP.py    2020-05-16 05:29:44.000000000 -0300
+++ /usr/lib/python3/dist-packages/policyd_rate_limit/policyd.py        2023-08-04 16:00:21.696376142 -0300
@@ -244,7 +244,13 @@
                     # Here we are limiting against sasl username, sender or source ip addresses.
                     # for each limit periods, we count the number of mails already send.
                     # if the a limit is reach, we change action to fail (deny the mail).
-                    for mail_nb, delta in config.limits_by_id.get(id, config.limits):
+                    verify_rule = config.limits_by_id.get(id)
+                    if verify_rule is None and '@' in id:
+                        # Try get by domain
+                        id_get_limit = id.split('@')[1]
+                    else:
+                        id_get_limit = id
+                    for mail_nb, delta in config.limits_by_id.get(id_get_limit, config.limits):
                         cur.execute(
                             (
                                 "SELECT COUNT(*) FROM mail_count "

````
In configuration file I used like this:
```YAML
limits_by_id:
    fqdn01:
        - [300, 3600]
        - [1500, 86400]
        - [7500, 604800]
    fqdn02:
        - [300, 3600]
        - [1500, 86400]
        - [7500, 604800]
    account@fqdn03:
        - [150, 3600] # 20230321000193
        - [800, 86400] # 20230321000193
        - [2500, 604800] # 20230321000193
```
